
/**   SQL SCRIPTS TO INSERT THE PRODUCT DETAILS **/


INSERT INTO PRODUCT_DETAIL (ID, PRODUCT_CODE,PRODUCT_NAME, PRICE)  VALUES (1, 'XJD-01' ,'ELECTRONICS PEN' ,'2000.00' );

INSERT INTO PRODUCT_DETAIL (ID, PRODUCT_CODE,PRODUCT_NAME, PRICE)  VALUES (2, 'XJD-02' ,'Laptop' ,'29000.00' );

INSERT INTO PRODUCT_DETAIL (ID, PRODUCT_CODE,PRODUCT_NAME, PRICE)  VALUES (3, 'XJD-03' ,'LED TV' ,'6500.00' );

INSERT INTO PRODUCT_DETAIL (ID, PRODUCT_CODE,PRODUCT_NAME, PRICE)  VALUES (4, 'XJD-04' ,'Mobile' ,'2200.00' );

INSERT INTO PRODUCT_DETAIL (ID, PRODUCT_CODE,PRODUCT_NAME, PRICE)  VALUES (5, 'XJD-05' ,'Cooler' ,'10000.00' );